name: 'Set workflow run name'
description: 'Update the workflow run name to include the provided version'
inputs:
  version:
    description: 'Version number to append to the workflow run name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update run name
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const version = '${{ inputs.version }}';
          await github.request('PATCH /repos/{owner}/{repo}/actions/runs/{run_id}', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
            name: `${context.workflow} - ${version}`,
          });
